In [45]:
# run this on the linux machine to turn each timestep into a csv file
import meshio
import numpy
import os
input_directory = "procData"

# Iterate through every file in every subdirectory of every subdirectory of a directory
for root, subdirectories, files in os.walk(input_directory):
    for patient in subdirectories:
        for root2, subdirectories2, files2 in os.walk(os.path.join(input_directory, patient)):
            for simulation in subdirectories2:
                for root3, subdirectories3, files3 in os.walk(os.path.join(input_directory, patient, simulation)):
                    for file in files3:
                        if file.endswith(".vtu"):
                            # Do not run if the file's name is Data_0011.vtu
                            if file.startswith("Data_0011"):
                                # Delete the file
                                os.remove(os.path.join(
                                    input_directory, patient, simulation, file))
                                continue
                            # Get the four digit number from the file name: Data_0000.vtu
                            number = int(file.split("_")[1].split(".")[0]) * 50

                            # Load the mesh
                            mesh = meshio.read(os.path.join(
                                input_directory, patient, simulation, file))

                            # Get the data from the mesh
                            points = mesh.points
                            density = numpy.expand_dims(
                                mesh.point_data["channel1"], axis=1)

                            # horizontally stack to become a 4 column matrix
                            stack = numpy.hstack((points, density))
                            # Write the data to a csv file
                            numpy.savetxt(os.path.join(input_directory, patient, simulation, str(
                                number) + ".csv"), stack, delimiter=",", fmt="%f")
                            print("Saved " + os.path.join(input_directory,
                                  patient, simulation, str(number) + ".csv"))
                            # output: x,y,z,density

                            # Delete the vtu file
                            # run this on the linux machine to turn each timestep into a csv file
                            os.remove(os.path.join(input_directory,
                                      patient, simulation, file))


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P7/P7_dat_5/300.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P7/P7_dat_5/350.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P7/P7_dat_5/250.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P7/P7_dat_5/200.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P7/P7_dat_5/500.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P7/P7_dat_5/0.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P7/P7_dat_5/50.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P7/P7_dat_5/150.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P7/P7_dat_5/100.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P7/P7_dat_5/450.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P7/P7_dat_5/400.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P1/P1_dat_5/300.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P1/P1_dat_5/350.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P1/P1_dat_5/250.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P1/P1_dat_5/200.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P1/P1_dat_5/500.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P1/P1_dat_5/0.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P1/P1_dat_5/50.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P1/P1_dat_5/150.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P1/P1_dat_5/100.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P1/P1_dat_5/450.csv


Warning: File contains cells that meshio cannot handle (type 11).

Saved procData/P1/P1_dat_5/400.csv


In [15]:
# run this on the linux machine to turn each timestep into a csv file
import meshio
import numpy
import os
input_directory = "procData/P7/p1 dat at random loc/"

mesh = meshio.read(input_directory + "Data_0001.vtu")
points = mesh.points
density = numpy.expand_dims(mesh.point_data["channel1"], axis=1)
# horizontally stack to become a 4 column matrix
stack = numpy.hstack((points, density))

stack2 = numpy.delete(stack,numpy.where(stack[:,3] == 0),axis=0)

print(stack2)

#numpy.savetxt("nozeros.csv", stack2, delimiter=",", fmt="%f")
#numpy.savetxt("wzeros.csv", stack2, delimiter=",", fmt="%f")

Warning: File contains cells that meshio cannot handle (type 11).

[[0.21875    0.375      0.4375     0.10212936]
 [0.15625    0.40625    0.4375     0.10000074]
 [0.1875     0.40625    0.4375     0.1       ]
 ...
 [0.5        0.5        0.71875    0.13324985]
 [0.5        0.53125    0.71875    0.10098906]
 [0.5        0.5625     0.71875    0.10500001]]
